### ISSUE TITLE
Unable to download WowAce addons with the newest version

### ISSUE THREAD

**Issue by alecjpav** [erikabp123/ClassicAddonManager#11]
When I go to try and add any addon on WowAce it fails giving me this error:
![2019-09-23_132503](https://user-images.githubusercontent.com/28431403/65459840-91925580-de05-11e9-8f04-7d26831ec720.jpg)

**Comment by erikabp123** [comment]
Hi, I am aware of this. This is a problem for curse and wowace (they are basically just copy pasted of each other). I will work on a solution tomorrow

**Comment by alecjpav** [comment]
Wonderful thanks so much!

**Comment by minikN** [comment]
Don't know if this is related, but this is what I get when tying to update addons after the update:

![image](https://user-images.githubusercontent.com/1888338/65547863-9b59ad00-df1a-11e9-87a0-f43a16d56ba3.png)

![image](https://user-images.githubusercontent.com/1888338/65547989-d78d0d80-df1a-11e9-8714-bc49d397546e.png)


Example error code:

```
Addon: WeaponSwingTimer
Author: LeftHandedGlove
URL: https://www.curseforge.com/wow/addons/weaponswingtimer
Branch: nullReleases: falseLast Updated: Sun Sep 01 16:27:08 CEST 2019
Last File Name: WeaponSwingTimer_LeftHandedGlove_(WeaponSwingTimer_V4.1.0.zip).zip
com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException: 403 Forbidden for https://www.curseforge.com/wow/addons/weaponswingtimer/files/all?filter-game-version=1738749986%3A67408
	at com.gargoylesoftware.htmlunit.WebClient.throwFailingHttpStatusCodeExceptionIfNecessary(WebClient.java:496)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:321)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:376)
	at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:361)
	at com.CAM.DataCollection.Scraper.scrape(Scraper.java:70)
	at com.CAM.DataCollection.Scraper.scrape(Scraper.java:56)
	at com.CAM.DataCollection.Scraper.<init>(Scraper.java:31)
	at com.CAM.DataCollection.CurseForgeScraper.<init>(CurseForgeScraper.java:37)
	at com.CAM.DataCollection.CurseForgeScraper.getOfficialScraper(CurseForgeScraper.java:33)
	at com.CAM.DataCollection.CurseForgeScraper.makeScraper(CurseForgeScraper.java:21)
	at com.CAM.HelperTools.UrlInfo.getCorrespondingScraper(UrlInfo.java:197)
	at com.CAM.AddonManagement.Addon.getScraper(Addon.java:81)
	at com.CAM.AddonManagement.Addon.checkForUpdate(Addon.java:56)
	at com.CAM.AddonManagement.AddonManager.updateAddons(AddonManager.java:57)
	at com.CAM.GUI.Controller.lambda$updateAction$4(Controller.java:223)
	at java.base/java.lang.Thread.run(Thread.java:835)
com.CAM.DataCollection.ScrapeException
	at com.CAM.DataCollection.Scraper.scrape(Scraper.java:78)
	at com.CAM.DataCollection.Scraper.scrape(Scraper.java:56)
	at com.CAM.DataCollection.Scraper.<init>(Scraper.java:31)
	at com.CAM.DataCollection.CurseForgeScraper.<init>(CurseForgeScraper.java:37)
	at com.CAM.DataCollection.CurseForgeScraper.getOfficialScraper(CurseForgeScraper.java:33)
	at com.CAM.DataCollection.CurseForgeScraper.makeScraper(CurseForgeScraper.java:21)
	at com.CAM.HelperTools.UrlInfo.getCorrespondingScraper(UrlInfo.java:197)
	at com.CAM.AddonManagement.Addon.getScraper(Addon.java:81)
	at com.CAM.AddonManagement.Addon.checkForUpdate(Addon.java:56)
	at com.CAM.AddonManagement.AddonManager.updateAddons(AddonManager.java:57)
	at com.CAM.GUI.Controller.lambda$updateAction$4(Controller.java:223)
	at java.base/java.lang.Thread.run(Thread.java:835)

```
