### ISSUE TITLE
tukui addons are broken 

### ISSUE THREAD

**Issue by d3aths** [erikabp123/ClassicAddonManager#24]
**Describe the bug**
addons from tukui are encountering errors and not updating

**To Reproduce**
add any tukui addon into the manager and then try to update

**Desktop (please complete the following information):**
windows 10

**Additional context**
this is also happening with other addon managers, according to cursebreaker, tukui api was partially disabled, but they have implemented some kind of workaround

**Comment by erikabp123** [comment]
hey, can you confirm that it is tukui and not curse? I was aware that curse would be transitioning to overwolf, but I have not heard of the tukui problems

**Comment by d3aths** [comment]
yup definitely anything from tukui is not updating for me.
[see screenshot here](https://i.ibb.co/9Yb0gsp/image.png)

i get this error with every tukui addon

```Addon: ElvUI
Author: Elv
URL: https://www.tukui.org/classic-addons.php?id=2
Branch: nullReleases: falseLast Updated: Fri Dec 04 15:23:37 NZDT 2020
Last File Name: ElvUI_Elv_(ElvUI-tukui).zip
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:913)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.google.gson.Gson.fromJson(Gson.java:773)
	at com.CAM.DataCollection.Tukui.TukuiAPI.getJsonObject(TukuiAPI.java:60)
	at com.CAM.DataCollection.Tukui.TukuiAPI.getRepoObject(TukuiAPI.java:69)
	at com.CAM.DataCollection.Tukui.TukuiAPI.<init>(TukuiAPI.java:30)
	at com.CAM.HelperTools.UrlInfo.getCorrespondingInfoRetriever(UrlInfo.java:208)
	at com.CAM.AddonManagement.Addon.getInfoRetriever(Addon.java:93)
	at com.CAM.AddonManagement.Addon.checkForUpdate(Addon.java:68)
	at com.CAM.AddonManagement.AddonManager.updateAddons(AddonManager.java:109)
	at com.CAM.GUI.Controller.lambda$updateAction$13(Controller.java:443)
	at java.base/java.lang.Thread.run(Thread.java:835)
com.CAM.DataCollection.ScrapeException
	at com.CAM.AddonManagement.AddonManager.updateAddons(AddonManager.java:126)
	at com.CAM.GUI.Controller.lambda$updateAction$13(Controller.java:443)
	at java.base/java.lang.Thread.run(Thread.java:835)```

**Comment by d3aths** [comment]
[cursebreaker ticket that confirms the api had been changed](https://github.com/AcidWeb/CurseBreaker/issues/255) can't find out any extra info about this online, nor on the tukui website. could help with the problem?

**Comment by erikabp123** [comment]
Fixed in new version
