### ISSUE TITLE
Java Error

### ISSUE THREAD

**Issue by Knomkrad** [erikabp123/ClassicAddonManager#27]
**Describe the bug**
It seems some addons have broken links. I have the problem with Titan panel [Reputation]
**To Reproduce**
1. Go to Update addons or start the program
Error:
java.util.NoSuchElementException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1492)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1513)
	at com.CAM.DataCollection.TwitchOwned.CurseForge.CurseForgeAPI.determineFileToUse(CurseForgeAPI.java:44)
	at com.CAM.DataCollection.TwitchOwned.CurseForge.CurseForgeAPI.<init>(CurseForgeAPI.java:39)
	at com.CAM.HelperTools.UrlInfo.getCorrespondingAPI(UrlInfo.java:204)
	at com.CAM.AddonManagement.Addon.getAPI(Addon.java:123)
	at com.CAM.AddonManagement.Addon.checkForUpdate(Addon.java:98)
	at com.CAM.AddonManagement.AddonManager.checkForUpdates(AddonManager.java:90)
	at com.CAM.GUI.Controller.checkForAddonUpdates(Controller.java:1634)
	at com.CAM.GUI.Controller.lambda$refreshAction$61(Controller.java:1601)
	at java.base/java.lang.Thread.run(Thread.java:835)

Titan panel is not updated.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windos 10 Pro
 - Browser Opera

**Additional context**
![2021_04_18_17_35_39_Window](https://user-images.githubusercontent.com/4005446/115151311-a3cd8780-a06c-11eb-9054-7cb2dc807619.png)

**Comment by erikabp123** [comment]
Which version of the manager are you using? and can you send me the errors file? It should be on the same level as the .exe

**Comment by erikabp123** [comment]
Upon review, I am unable to find the addon in question through the in-app search. I have added some changes which should fix the issue you encountered, but in order to properly test it I would ask that you send your "data/CLASSIC/managed.json" file to me.

**Comment by Knomkrad** [comment]
Here is my managed.json
[managed.zip](https://github.com/erikabp123/ClassicAddonManager/files/6408387/managed.zip)
