### ISSUE TITLE
Unexpected Error Updating

### ISSUE THREAD

**Issue by KJee85** [erikabp123/ClassicAddonManager#31]
Throwing error when updating addons

java.lang.NullPointerException
	at com.CAM.DataCollection.TwitchOwned.CurseForge.CurseForgeAPI.getLastUpdated(CurseForgeAPI.java:128)
	at com.CAM.AddonManagement.Addon.checkForUpdate(Addon.java:97)
	at com.CAM.AddonManagement.AddonManager.checkForUpdates(AddonManager.java:94)
	at com.CAM.GUI.Controller.checkForAddonUpdates(Controller.java:1631)
	at com.CAM.GUI.Controller.lambda$updateAction$13(Controller.java:545)
	at java.base/java.lang.Thread.run(Thread.java:835)

**Comment by KJee85** [comment]
This seems to be working now, suppose it's possible it was on curse api end, but maybe error could be clearer when that is the case.
